### ISSUE TITLE
Tests fail (with newer Mojolicious)

### ISSUE THREAD

**Issue by eserte** [viliampucik/Mojolicious-Plugin-DocRenderer#5]
Test suite fails with newer Mojolicious versions. Statistical analysis shows that tests fail for Mojolicious 6.26 and later. Last passing tests on my machines was with Mojolicious 6.18.

**Comment by viliampucik** [comment]
I am sorry about that. Should be fixed in e342118b3377b8b6481327cecb03d38c0f841b9e.
