### ISSUE TITLE
Tests fail in "t/basic.pl" with Mojolicious v7.43

### ISSUE THREAD

**Issue by bignmllc** [viliampucik/Mojolicious-Plugin-DocRenderer#6]
I am interested in using this plugin to document my Mojolicious project. The script "t/basic.pl" fails due to the use of the "slurp" method that is no longer exported by the Mojo::Util module. Here included are the relevant error lines printed during installation:

Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.pl
t/basic.pl .. "slurp" is not exported by the Mojo::Util module
Can't continue after import errors at lib/Mojolicious/Plugin/DOCRenderer.pm line 10.
BEGIN failed--compilation aborted at lib/Mojolicious/Plugin/DOCRenderer.pm line 10.
Compilation failed in require at (eval 74) line 1.
# Looks like your test exited with 255 before it could output anything.
t/basic.pl .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 9/9 subtests 

The error appears to be inside the source code of the plugin, and not the test code.

**Comment by viliampucik** [comment]
I am sorry about that. Should be fixed by e342118b3377b8b6481327cecb03d38c0f841b9e. Newer version of Perl module should appear in CPAN soon.
